title: Tara Liu # your name (or website title) here
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  ğŸ‘‹ Hi there! My name is Tara. I'm a double major graduate student at Georgia Tech and a data governance analyst at MARTA.
  <br><br>
  ğŸ‘©ğŸ»â€ğŸ’» Iâ€™m a team player with a strong interest in data. I developed my passion for technology when I discovered how big data can transform transit systems. Since then, I've pursued this interest with the help of programs like Rewriting the Code.
  
  ğŸ‘¤ Along with my passion for technology, I've developed a strong desire to contribute to social good throughout my life. I enjoy using technology to generate insights that can improve urban mobility, women's rights, inequality, and public health.
  <br><br>
  âœ¨ I'm currently focused on machine learning, geo-spatial data science & engineering, and GIS.
  
  ğŸ›  Here's What I'm Working on Right Now:
  
  ğŸ“šVolunteering at Chayn, an NGO that helps women experiencing abuse find the information and support they need to regain control of their lives.
  
  ğŸ“šActively participating in CTF (cybersecurity competitions).
 
  <br><br>
  <a href="https://www.linkedin.com/in/tara-tingyu-liu/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
